apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: nexuses.navigator.avito.ru
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: navigator.avito.ru
  version: v1
  # list of versions supported by this CustomResourceDefinition
  versions:
  - name: v1
    # Each version can be enabled/disabled by Served flag.
    served: true
    # One and only one version must be marked as the storage version.
    storage: true
  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: nexuses
    # singular name to be used as an alias on the CLI and for display
    singular: nexus
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: Nexus
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - nx
  preserveUnknownFields: false
  validation:
    openAPIV3Schema:
      type: object
      properties:
        spec:
          type: object
          properties:
            appName:
              type: string
            services:
              type: array
              items:
                type: object
                properties:
                  name:
                    type: string
                  namespace:
                    type: string
